### ISSUE TITLE
ippusbxd: <746945408>Error: recv failed with err 11:Resource temporarily unavailable

### ISSUE THREAD

**Issue by jiape** [tillkamppeter/ippusbxd#14]
**Syslog:**
Aug  9 22:22:31 jiapeng-HP-Z6-G4-Workstation ippusbxd: <746945408>Error: recv failed with err 11:Resource temporarily unavailable
Aug  9 22:22:39 jiapeng-HP-Z6-G4-Workstation ippusbxd: <536865648>Error: USB timed out, giving up waiting for more data
Aug  9 22:22:45 jiapeng-HP-Z6-G4-Workstation ippusbxd: <746945408>Error: recv failed with err 11:Resource temporarily unavailable
Aug  9 22:22:46 jiapeng-HP-Z6-G4-Workstation ippusbxd: <536865648>Error: USB timed out, giving up waiting for more data
Aug  9 22:22:51 jiapeng-HP-Z6-G4-Workstation ippusbxd: <536865664>Error: recv failed with err 11:Resource temporarily unavailable
Aug  9 22:23:04 jiapeng-HP-Z6-G4-Workstation ippusbxd: <536865648>Error: USB timed out, giving up waiting for more data

**OS:**
Ubuntu 16.04.4 LTS (GNU/Linux 4.15.0-30-generic x86_64)

**Comment by tillkamppeter** [comment]
I have checked through this repository which is not used any more to see whether there are any valuable pull requests or issues which got accidentally posted here and then overlooked.
The official repository is https://github.com/OpenPrinting/ippusbxd
Please test the code from there and if you encounter the same bug there, please re-post your bug report there. Thank you very much.
